### PR TITLE
Add password validation

### PR DESCRIPTION
**Pull request by Ingeborgausteid**
Updated `src > controllers > user.js` to include a `validatePassword` function. The function takes in the request body, and checks if the password matches the set requirements. If requirements are not met, it returns an error.

### CODE REVIEW

**Comment by JHalvor** [comment]
user field validations should be in ```src > middleware > auth``` i suggest creating a validateUserFields or validateUserInputs function that will be called from create and update/patch routes for users ```src > routes> user```.
This function can contain validation for both password and email

**Comment by Ingeborgausteid** [comment]
Added and updated `src > middleware> user.js` to include a `validateUser` function with password validation. The function takes in the request body, and checks if the password matches the set requirements. If requirements are not met, it returns an error.

Updated `routes > user.js` to include `validateUser` in router.post and router.patch.

**Review by JHalvor — APPROVED** [review]
Looks good and is tested

**Review by Brandsegg — DISMISSED** [review]
very good

**Comment by JHalvor** [comment]
@allendewilzin @uerbzr please look over one of you and approve.
only routes, middleware's user.js is actually edited, not controller's user.js

**Review by JHalvor — APPROVED** [review]
Nice! looks good now

**Review by Brandsegg — APPROVED** [review]
Good!

**Pull request merged**
