### PR TITLE
52 update create endpoint for cohort

### PR DESCRIPTION
**Pull request by eyvmal**
Modified:
- routes/cohort.js
- controllers/cohort.js
- domain/cohort.js
- docs/openapi.yml
---
Updated the create function to use the save function from the Cohort class like how its made in the domain/user.js
The endpoint is protected so only teachers can create new cohorts.
The swagger doc is updated accordingly.

### CODE REVIEW

**Review by Brandsegg — APPROVED** [review]
very nice, Eyvind!

**Review by JHalvor — APPROVED** [review]
tested and works!

**Review by Brandsegg — APPROVED** [review]
Very nice again, Eyvind!

**Review by JHalvor — APPROVED** [review]
looks good and is tested, works!

**Review by Brandsegg — APPROVED** [review]
Very Very nice again, Eyvind!

**Review by JHalvor — APPROVED** [review]
lgtm

**Review by Brandsegg — APPROVED** [review]
Very very very good, Eyvind!

**Pull request merged**
